#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

from common import (
    PROMPT_KEYS,
    normalized_json_string,
    read_jsonl,
    utc_now,
    validate_stage2_json,
    write_json,
    write_jsonl,
)


USER_CONTENT = "<image>\nIs this image real or generated by AI? Please analyze visual forensic evidence and output the structured JSON judgment."


def load_stage1_by_id(rows: list[dict]) -> dict:
    grouped = {}
    for row in rows:
        sample_id = row.get("id")
        if not sample_id:
            continue
        if isinstance(row.get("stage1"), dict):
            grouped[sample_id] = row
            continue
        prompt_id = row.get("prompt_id")
        if prompt_id in PROMPT_KEYS and row.get("prompt_valid", True):
            bucket = grouped.setdefault(
                sample_id,
                {
                    "id": sample_id,
                    "stage1": {},
                    "model": row.get("model"),
                    "model_path": row.get("model_path"),
                },
            )
            bucket["stage1"][prompt_id] = {
                "prompt": row.get("prompt", ""),
                "output": row.get("raw_text", "").strip(),
            }
    return grouped


def stage2_assistant_content(row: dict) -> str:
    if isinstance(row.get("stage2_json"), dict):
        return normalized_json_string(row["stage2_json"])
    if isinstance(row.get("stage2_json_string"), str):
        parsed = json.loads(row["stage2_json_string"])
        return normalized_json_string(parsed)
    raise ValueError("stage2 row missing validated JSON")


def parse_args():
    parser = argparse.ArgumentParser(description="Build train_sft.jsonl from strict validated Stage2 rows.")
    parser.add_argument("--output_dir", default="output_sidset_thinkfake_gpt55_xhigh")
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--reasoning_effort", default="xhigh")
    return parser.parse_args()


def main():
    args = parse_args()
    output_dir = Path(args.output_dir).expanduser().resolve()
    logs_dir = output_dir / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    manifest_by_id = {row["id"]: row for row in read_jsonl(output_dir / "manifest.jsonl")}
    stage1_by_id = load_stage1_by_id(read_jsonl(output_dir / "stage1_valid.jsonl"))
    stage2_rows = read_jsonl(output_dir / "stage2_valid.jsonl")

    train_rows = []
    skipped_missing_stage1 = []
    skipped_invalid_assistant_json = []

    for stage2 in stage2_rows:
        sample_id = stage2["id"]
        stage1 = stage1_by_id.get(sample_id)
        manifest = manifest_by_id.get(sample_id, stage2)
        if not stage1 or not all(k in stage1.get("stage1", {}) for k in ["prompt1", "prompt2", "prompt3"]):
            skipped_missing_stage1.append({"id": sample_id, "reason": "missing_stage1_prompt_outputs"})
            continue
        try:
            assistant_content = stage2_assistant_content(stage2)
            valid, _, _, errors, _ = validate_stage2_json(assistant_content, manifest["label"])
        except Exception as exc:  # noqa: BLE001
            valid = False
            errors = [str(exc)]
            assistant_content = ""
        if not valid:
            skipped_invalid_assistant_json.append({"id": sample_id, "validation_errors": errors})
            continue
        row = {
            "id": sample_id,
            "image": manifest.get("image_path", stage2.get("image_path")),
            "label": manifest["label"],
            "messages": [
                {"role": "user", "content": USER_CONTENT},
                {"role": "assistant", "content": assistant_content},
            ],
            "thinkfake_stage1": {
                "prompt1": stage1["stage1"]["prompt1"]["output"],
                "prompt2": stage1["stage1"]["prompt2"]["output"],
                "prompt3": stage1["stage1"]["prompt3"]["output"],
            },
            "generator_model": stage2.get("model") or args.model,
            "reasoning_effort": stage2.get("reasoning_effort") or args.reasoning_effort,
        }
        if len(row["messages"]) != 2 or row["messages"][0]["role"] != "user" or row["messages"][1]["role"] != "assistant":
            skipped_invalid_assistant_json.append({"id": sample_id, "validation_errors": ["invalid_messages_shape"]})
            continue
        json.loads(row["messages"][1]["content"])
        train_rows.append(row)

    train_path = output_dir / "train_sft.jsonl"
    write_jsonl(train_path, train_rows)
    if skipped_missing_stage1:
        write_jsonl(logs_dir / "build_train_skipped_missing_stage1.jsonl", skipped_missing_stage1)
    if skipped_invalid_assistant_json:
        write_jsonl(logs_dir / "build_train_skipped_invalid_assistant_json.jsonl", skipped_invalid_assistant_json)

    report = {
        "total_stage2_valid": len(stage2_rows),
        "total_written": len(train_rows),
        "skipped_missing_stage1": len(skipped_missing_stage1),
        "skipped_invalid_assistant_json": len(skipped_invalid_assistant_json),
        "real_written": sum(1 for row in train_rows if row["label"] == "REAL"),
        "fake_written": sum(1 for row in train_rows if row["label"] == "AI-GENERATED"),
        "built_at": utc_now(),
    }
    write_json(logs_dir / "build_train_report.json", report)
    print(report)


if __name__ == "__main__":
    main()
